---
title: "Dynamic IRT Model with an example from Political Science - a replication of Martin, Quinn's Supreme Court Model"
author: "Guilherme Jardim Duarte"
date: "17 de junho de 2016"
bibliography: bibliography.bibtex
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This is a case study and tutorial regarding how to code a Dynamic Bayesian Item Response Theory for Ideal Points in Political Science. We will replicate the paper "Dynamic Ideal Point Estimation via Markov Chain Monte Carlo for the U.S. Supreme Court, 1953–1999", by Andrew D. Martin and Kevin M. Quinn, published in Political Analysis - 2001 [@martin2002dynamic]. It consists of four parts. Firsly, we will explain what is an Ideal Point Model and what extent a Item Response Theory is related to it. Then, 

# Introduction 

## Ideal Point Modeling and IRT Estimation

Ideal Point Models are standard models in Political Science. They assume that politicans have preferences represented by utility functions in a vectorial space of $\mathbb{R}$. According to those models, one actor A will choose between two alternatives x (change policy) and y (status quo) through their distance from his ideal point. Suppose, for example, two congressmen, A and B, are called to vote an issue laid down to allow abortion in cases of rape and serious harm to woman's body in a country where ending pregnancy is a serious crime . The first one strongly opposes abortion, whereas the second one is favorable to it in any case. Suppose in status quo abortions are not allowed in any situation. In this case, congressman A will oppose the change, while congressman B will vote for it.

For a formalization of the Ideal Model Point, the reader would like to see [clinton2004statistical] or [@martin2002dynamic].

We employ Item Response Theory Model here to estimate those latent ideal point estimation. We will model the probability of voting 1 (yea) or 0 (nay) is given by $y_{ij}$, in which $i$ stands for the rollcall and $j$ for the politician. The model is represented by: $$y_{ij} = \alpha_i - \beta_i * \theta_j $$


